inshop/app1/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     url(r'^$', views.HomePage.as_view(), name="bits in bytes"),
     url(r'product/(?P<pk>\d+)/$', views.product_details, name="product_details"),
     url(r'account/profile/$', views.Profile.as_view(), name="profile"),
     url(r'account/profile/change_data$', views.user_change_info, name="profile_correct"),
     url(r'account/basket$', views.basket, name="basket"),
     url(r'account/basket/(?P<pk>\d+)$', views.basket, name="basket"),
     url(r'search/$', views.Search.as_view(), name='searching'),
     url(r'account/basket/buy_one/(?P<pk>\d+)$', views.buy_one_product, name="product_buy_one"),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

inshop/inshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from app1.forms import CustomUserForm
from api.views import ProductViewSet, BasketViewSet
from django_registration.backends.one_step.views import RegistrationView
from django.conf.urls.static import static
from rest_framework import routers
from . import settings


router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)
router.register(r'basket', BasketViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app1.urls')),
    url(r'^accounts/register/$',
        RegistrationView.as_view(form_class=CustomUserForm),
        name='django_registration_register',),
    url(r'^accounts/', include('django_registration.backends.one_step.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/v1/', include(router.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inshop/app1/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    region = models.CharField(max_length=60, help_text="Oblast Vashego projivaia", blank=True)
    city = models.CharField(max_length=60, help_text="Gorod Vashego projivaia", blank=True)
    address = models.CharField(max_length=80, help_text="Adress Vashego projivaia", blank=True)
    delivery = models.CharField(max_length=80, help_text="Predpochitaemaya slujba dostavki i nomer otdelenia",
                                blank=True)


class ShoppingList (models.Model):
    buyer = models.ForeignKey('User', on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    data_of_buy = models.DateTimeField(auto_now_add=True)
    payed_or_not = models.CharField(max_length=80, default="No")
    product_name = models.CharField(max_length=80)


class Product(models.Model):
    MANUFACT = (
        ("SN", "Sony"),
        ("SM", "Samsung"),
        ("PS", "Panasonic"),
        ("SW", "Swen"),
        ("AP", "Apple"),
        ("SE", "Sony Ericson"),
        ("XM", "Xiaomi"),
    )

    COLOR = (
        ("BL", "Black"),
        ("WT", "White"),
        ("BE", "Blue"),
        ("GR", "Green"),
        ("PN", "Pink"),
    )

    TYPE = (
        ("BL", "Bluetooth"),
        ("WR", "Wire"),
    )

    TYPE_CONNECTOR = (
        ("3.5", "Mini-jack 3.5 mm"),
        ("LG", "Lightning"),
        ("2.0", "Bluetooth 2.0"),
        ("2.1", "Bluetooth 2.1"),
        ("3.0", "Bluetooth 3.0"),
    )

    name = models.CharField(max_length=60)
    manufacturer = models.CharField(max_length=10, choices=MANUFACT)
    color = models.CharField(max_length=10, choices=COLOR)
    bluetooth_or_wire = models.CharField(max_length=10, choices=TYPE)
    connection_range = models.CharField(max_length=60, blank=True, default="0")
    work_time = models.CharField(max_length=60, blank=True, default="0")
    warranty = models.IntegerField()
    wire_lenght = models.DecimalField(max_digits=4, decimal_places=1, blank=True, default="0", )
    type_connector = models.CharField(max_length=10, choices=TYPE_CONNECTOR)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    photo = models.ImageField(blank=True, upload_to="media/", default="None")

    def __str__(self):
        return self.name

inshop/app1/forms.py
from django_registration.forms import RegistrationForm
from .models import User, ShoppingList, Product
from django import forms


class CustomUserForm(RegistrationForm):
    class Meta(RegistrationForm.Meta):
        model = User


class AddBuy(forms.ModelForm):
    class Meta:
        model = ShoppingList
        fields = []


class ChangeWarranty(forms.ModelForm):
    class Meta:
        model = Product
        fields = []


class ChangeUserInformation(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'region', 'city', 'address', 'delivery']

inshop/app1/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils.datastructures import MultiValueDictKeyError
from .models import Product, ShoppingList, User
from .forms import AddBuy, ChangeWarranty, ChangeUserInformation
from django.utils import timezone
from django.views.generic.base import TemplateView
from functools import wraps


class HomePage(TemplateView):

    template_name = "app1/Main.html"

    def get_context_data(self, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)
        productrs = Product.objects.all()
        current_page = Paginator(productrs, 10)
        page = self.request.GET.get('page', 1)
        try:
            context['Products'] = current_page.page(page)
        except PageNotAnInteger:
            context['Products'] = current_page.page(1)
        except EmptyPage:
            context['Products'] = current_page.page(current_page.num_pages)
        return context


class Search(TemplateView):

    template_name = "app1/search.html"

    def get_context_data(self, **kwargs):
        context = super(Search, self).get_context_data(**kwargs)
        question = self.request.GET.get('search')
        if question is not None:
            search_products = Product.objects.filter(name__contains=question)
            context['last_question'] = '?search=%s' % question
            print(context['last_question'])
            current_page = Paginator(search_products, 10)
            page = self.request.GET.get('page', 1)
            try:
                context['products_lists'] = current_page.page(page)
            except PageNotAnInteger:
                context['products_lists'] = current_page.page(1)
            except EmptyPage:
                context['products_lists'] = current_page.page(current_page.num_pages)

        return context


class Profile(TemplateView):

    template_name = "app1/profile.html"

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        pk = self.request.user.id
        user_data = get_object_or_404(User, pk=pk)
        context['first_name'] = user_data.first_name
        context['last_name'] = user_data.last_name
        context['region'] = user_data.region
        context['city'] = user_data.city
        context['address'] = user_data.address
        context['delivery'] = user_data.delivery
        return context


def product_details(request, pk):
    prod = get_object_or_404(Product, pk=pk)
    form = AddBuy()
    photo = str(prod.photo)
    price = int(prod.price * 100)
    warr = ChangeWarranty(request.POST, instance=prod)
    if request.method == 'POST':
        form = form.save(commit=False)
        form.buyer = request.user
        form.buyer_id = request.user.id
        form.product_id = prod.id
        form.price = prod.price
        form.data_of_buy = timezone.now()
        form.product_name = prod.name
        try:
            import stripe
            stripe.api_key = "sk_test_KoPBXsif8wO9pa9GPKU9qsz6"
            stripe.Charge.create(
                amount=price,
                currency="usd",
                source=request.POST['stripeToken'],
                description="Test payment",
            )
            form.payed_or_not = 'Yes'
        except MultiValueDictKeyError:
            form.payed_or_not = 'No'
        form.save()
        warr = warr.save()
        warr.warranty = prod.warranty - 1
        warr.save()
        return redirect('bits in bytes')
    else:
        pass
    return render(request, 'app1/prod_detail.html', {'prod': prod, 'warr': warr, 'photo': photo, 'price': price})


def user_change_info(request):
    user = request.user
    if request.method == 'POST':
        form = ChangeUserInformation(request.POST, instance=user)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
        return redirect('profile')
    else:
        form = ChangeUserInformation(instance=user)
    return render(request, 'app1/profile_correct.html', {'form': form})


def basket(request, pk=None):
    prod_in_bask = ShoppingList.objects.filter(buyer_id=request.user.id, payed_or_not='No')
    story_of_buy = ShoppingList.objects.filter(buyer_id=request.user.id, payed_or_not='Yes')
    price = 0
    for prod in prod_in_bask:
        price = price + prod.price
    price = int(price * 100)
    if pk is not None:
        dell_pod = ShoppingList.objects.filter(id=pk)
        del_prod_obj = dell_pod.get()
        prod = get_object_or_404(Product, pk=del_prod_obj.product_id)
        dell_pod.delete()
        warr = ChangeWarranty(request.POST, instance=prod)
        warr = warr.save()
        warr.warranty = prod.warranty + 1
        warr.save()
        return redirect('basket')
    elif request.method == 'POST':
        import stripe
        stripe.api_key = "sk_test_KoPBXsif8wO9pa9GPKU9qsz6"
        if request.method == 'POST':
            stripe.Charge.create(
                amount=price,
                currency="usd",
                source=request.POST['stripeToken'],
                description="Test payment",
            )
        for prod in prod_in_bask:
            form = AddBuy(request.POST, instance=prod)
            if form.is_valid():
                form = form.save(commit=False)
                form.payed_or_not = "Yes"
                form.data_of_buy = timezone.now()
                form.save()
        return redirect('basket')
    else:
        pass
    return render(request, 'app1/basket.html', {'prod_in_bask': prod_in_bask, 'price': price, 'story': story_of_buy,})


def buy_one_product(request, pk):
    product = get_object_or_404(ShoppingList, pk=pk)
    product_data = get_object_or_404(Product, pk=product.product_id)
    form = AddBuy(request.POST, instance=product)
    price = int(product_data.price * 100)
    import stripe
    stripe.api_key = "sk_test_KoPBXsif8wO9pa9GPKU9qsz6"
    if request.method == 'POST':
        stripe.Charge.create(
            amount=price,
            currency="usd",
            source=request.POST['stripeToken'],
            description="Test payment",
        )
        if form.is_valid():
            form = form.save(commit=False)
            form.payed_or_not = "Yes"
            form.data_of_buy = timezone.now()
            form.save()
        return redirect('basket')
    return render(request, 'app1/buy_one.html', {'form': form, 'product': product,
                                                         'prod': product_data, 'price': price})

inshop/app1/templates/app1/Main.html
{% extends "app1/base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'app1/css/main.css'%}">
<title>B&B main</title>
{% endblock %}
{% block content %}
<div>
    <br>
    <br>
    <table border="2" width="100%" cellpadding="5">
        <tr>
            <th>Photo</th>
            <th>Name</th>
            <th>Manufacturer</th>
            <th>Bluetooth or wire</th>
            <th>Connection type</th>
            <th>Price</th>
            <th>More information</th>
         </tr>
        {% for prod in Products %}
        <tr>
        {% if prod.photo != 'None' %}
            <th><img src="{{ prod.photo.url }}" class="picture"></th>
        {% else %}
            <th><img src="{% static 'images/non_img.jpg'%}" class="picture"></th>
        {% endif %}
            <th>{{ prod.name}}</th>
            <th>{{ prod.get_manufacturer_display }}</th>
            <th>{{ prod.get_bluetooth_or_wire_display}} </th>
            <th>{{ prod.get_type_connector_display}} </th>
            <th>{{ prod.price}} </th>
            <th><a href="{% url 'product_details' pk=prod.pk %}" class="buy-link">See more</a></th>
        </tr>
        {% endfor %}
    </table>
     {% bootstrap_pagination Products %}
</div>
{% endblock %}

inshop/app1/templates/app1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'app1/css/base.css'%}">
    {% block head %}
    {% endblock %}
</head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="navbar-container">
                <a class="navbar-brand" href="/">Bits in bytes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  {% if user.is_authenticated %}
                   <li class="nav-item active">
                     <span class="navbar-text" style="font-size: 20px">Hello, <a href="{% url 'profile' %}">{{user.username}}!</a></span>
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'logout' %}" style="font-size: 20px">Logout</a>
                      </li>
                    {% if user.is_staff == 1 %}
                      <li class="nav-item active">
                        <a class="nav-link" href="/admin/" style="font-size: 20px">Admin</a>
                      </li>
                  {% endif %}
                  {% elif not user.is_authenticated %}
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'django_registration_register' %}">Registration<span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="/admin/">Admin</a>
                  </li>
                  {% endif %}
                </ul>
                <div>
                  {% if user.is_authenticated %}
                        <div class="navbar-text">in your <a href="{% url 'basket' %}">basket</a>: {{user.basket_state}}</div>
                  {% elif not user.is_authenticated %}
                  {% endif %}
                </div>
                <div>
                    <form class="form-inline my-2 my-lg-0" action="{% url 'searching' %}" method="get">
                      <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
                </div>
            </div>
        </nav>
    <div class="main-content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

inshop/app1/templates/app1/basket.html
{% extends "app1/base.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'app1/css/basket.css'%}">
<title>B&B Your basket</title>
{% endblock %}
{% block content %}
<br>
<br>
<ul class="nav nav-tabs">
  <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#panel1">Basket</a></li>
  <li class="nav-item" ><a class="nav-link" data-toggle="tab" href="#panel2">History of buy</a></li>
</ul>
<div class="tab-content">
  <div id="panel1" class="tab-pane fade show active">
     <table border="2" width="100%" cellpadding="5">
        <tr>
            <th>Name</th>
            <th>Data of add</th>
            <th>Price</th>
            <th>Is payed?</th>
            <th>Delete</th>
            <th>Pay</th>
         </tr>
       {% for prod in prod_in_bask %}
        <tr>
        <td>{{ prod.product_name}}</td>
        <td>{{ prod.data_of_buy }}</td>
        <td>{{ prod.price}} </td>
        <td>{{ prod.payed_or_not}} </td>
        <td><a href="{% url 'basket' pk=prod.id %}">Delete</a></td>
        <td><a href="{% url 'product_buy_one' pk=prod.id %}">Buy only that</a></td>
      </tr>
        {% endfor %}
          <tr>
            <th></th>
            <th>Total price</th>
            <th>Price</th>
            <th></th>
            <th>Buy all</th>
            <th>
                <form action="{% url 'basket' %}"  method="POST">
                    {% csrf_token %}
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="pk_test_4d82ss51WQYwuCciwz4i5ude"
                data-amount="{{ price }}"
                data-name="Sample Charge"
                data-description="test"
                data-currency="usd">
                </script>
                </form>
             </th>
         </tr>
    </table>
  </div>
  <div id="panel2" class="tab-pane fade">
    <table border="2" width="100%" cellpadding="5">
        <tr>
            <th>Name</th>
            <th>Data of buy</th>
            <th>Price</th>
            <th>Is payed?</th>
         </tr>
       {% for element in story %}
        <tr>
        <td>{{ element.product_name}}</td>
        <td>{{ element.data_of_buy }}</td>
        <td>{{ element.price}} </td>
        <td>{{ element.payed_or_not}} </td>
      </tr>
        {% endfor %}
    </table>
  </div>
</div>

{% endblock %}

inshop/app1/templates/app1/buy_one.html
{% extends "app1/base.html" %}
{% load bootstrap %}
{% load static %}
{% block head %}
<title>B&B buy {{ prod.name }}</title>
{% endblock %}
{% block content %}
<div>
    <br>
    <br>
    <img src="{{ prod.photo.url }}" style="height: 300px; width: 300px">
    <br>
    <br>
    <table border="2" width="30%" cellpadding="10">
        <tr>
            <td>Product name</td>
            <td>{{ prod.name }}</td>
        </tr>
        <tr>
            <td>Manufacturer</td>
            <td>{{ prod.get_manufacturer_display }}</td>
        </tr>
        <tr>
            <td>Color of device</td>
            <td>{{ prod.get_color_display }}</td>
        </tr>
        <tr>
            <td>Bluetooth or wire</td>
            <td>{{ prod.get_bluetooth_or_wire_display }}</td>
        </tr>
        {% if prod.bluetooth_or_wire == 'BL' %}
        <tr>
            <td>Conection range</td>
            <td>{{ prod.connection_range }}</td>
        </tr>
        <tr>
            <td>Work time</td>
            <td>{{ prod.work_time }}</td>
        </tr>
        {% elif prod.bluetooth_or_wire == 'WR' %}
        <tr>
            <td>Wire length</td>
            <td>{{ prod.wire_lenght }}m</td>
        </tr>
        {% endif %}
        <tr>
            <td>Type of connection</td>
            <td>{{ prod.get_type_connector_display }}</td>
        </tr>
        <tr>
            <td>Price</td>
            <td>{{ prod.price }}</td>
        </tr>
    </table>
    <br>
    <form action="{% url 'product_buy_one' pk=product.id %}" method="POST">
        {% csrf_token %}
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="pk_test_4d82ss51WQYwuCciwz4i5ude"
                data-amount="{{ price }}"
                data-name="InShop"
                data-description="test"
                data-currency="usd">
        </script>
    </form>
</div>
{% endblock %}

inshop/app1/templates/app1/prod_detail.html
{% extends "app1/base.html" %}
{% load bootstrap %}
{% load static %}
{% block head %}
<title>B&B {{ prod.name }}</title>
{% endblock %}
{% block content %}
<div>
    <br>
    <br>
    <img src="{{ prod.photo.url }}" style="height: 300px; width: 300px">
    <br>
    <br>
    <table border="2" width="30%" cellpadding="10">
        <tr>
            <td>Product name</td>
            <td>{{ prod.name }}</td>
        </tr>
        <tr>
            <td>Manufacturer</td>
            <td>{{ prod.get_manufacturer_display }}</td>
        </tr>
        <tr>
            <td>Color of device</td>
            <td>{{ prod.get_color_display }}</td>
        </tr>
        <tr>
            <td>Bluetooth or wire</td>
            <td>{{ prod.get_bluetooth_or_wire_display }}</td>
        </tr>
        {% if prod.bluetooth_or_wire == 'BL' %}
        <tr>
            <td>Conection range</td>
            <td>{{ prod.connection_range }}</td>
        </tr>
        <tr>
            <td>Work time</td>
            <td>{{ prod.work_time }}</td>
        </tr>
        {% elif prod.bluetooth_or_wire == 'WR' %}
        <tr>
            <td>Wire length</td>
            <td>{{ prod.wire_lenght }}m</td>
        </tr>
        {% endif %}
        <tr>
            <td>Type of connection</td>
            <td>{{ prod.get_type_connector_display }}</td>
        </tr>
        <tr>
            <td>Price</td>
            <td>{{ prod.price }}</td>
        </tr>
    </table>
</div>
<br>
    {% if user.is_authenticated%}
        {% if prod.warranty > 0 %}
            <ul class="buttons">
                <li>
                    <form method="post">
                        {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Add to basket">
                    </form>
                </li>
                <li>
                    <form  action="{% url 'product_details' pk=prod.id %}" method="POST">
                        {% csrf_token %}
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                data-key="pk_test_4d82ss51WQYwuCciwz4i5ude"
                                data-amount="{{ price }}"
                                data-name="InShop"
                                data-description="test"
                                data-currency="usd">
                        </script>
                    </form>
                </li>
            </ul>
        {% elif prod.warranty <= 0 %}
            <td>Product sold out </td>
        {% endif %}
    {% else %}
        <td>You have to login to buy something</td>
    {% endif %}
{% endblock %}

inshop/app1/templates/app1/profile.html
{% extends "app1/base.html" %}

{% block head %}
<title>B&B Your profile</title>
{% endblock %}
{% block content %}
    <br>
<br>
<div>
  <table border="2" width="30%" cellpadding="10">
    <tr>
      <td>Your first name</td>
      <td>{{ first_name }}</td>
    </tr>
    <tr>
      <td>Your last name </td>
      <td>{{ last_name }}</td>
    </tr>
    <tr>
      <td>Your region</td>
      <td>{{ region }} </td>
    </tr>
    <tr>
      <td>Your city</td>
      <td>{{ city }} </td>
    </tr>
    <tr>
      <td>Your home address</td>
      <td>{{ address }} </td>
    </tr>
    <tr>
      <td>prefer delivery company and number of department</td>
      <td>{{ delivery }} </td>
    </tr>
  </table>
  <div><a href="{% url 'profile_correct'%}">Correct</a></div>
</div>
{% endblock %}

inshop/app1/templates/app1/profile_correct.html
{% extends "app1/base.html" %}
{% load bootstrap %}

{% block head %}
<title>B&B Your profile correct</title>
{% endblock %}
{% block content %}
<br>
    <form method="post">
        {% csrf_token %}
            {{ form|bootstrap }}
    <input type="submit" class="btn btn-primary" value="Save">
    </form>
{% endblock %}

inshop/app1/templates/app1/search.html
{% extends 'app1/base.html' %}
{% load bootstrap %}
{% load bootstrap4 %}
{% load static %}
{% block head %}
<title>B&B search</title>
{% endblock %}
{% block content %}
    <h1>Search</h1>
    {% if products_lists %}
       <table border="2" width="100%" cellpadding="5">
            <tr>
                <th>Photo</th>
                <th>Name</th>
                <th>Manufacturer</th>
                <th>Bluetooth or wire</th>
                <th>Connection type</th>
                <th>Price</th>
                <th>More information</th>
             </tr>
            {% for prod in products_lists %}
            <tr>
            {% if prod.photo != 'None' %}
                <th><img src="{{ prod.photo.url }}" class="picture" style="height: 150px; width: 150px"></th>
            {% else %}
                <th><img src="{% static 'images/non_img.jpg'%}" class="picture" style="height: 150px; width: 150px"></th>
            {% endif %}
                <th>{{ prod.name}}</th>
                <th>{{ prod.manufacturer }}</th>
                <th>{{ prod.bluetooth_or_wire}} </th>
                <th>{{ prod.type_connector}} </th>
                <th>{{ prod.price}} </th>
                <th><a href="{% url 'product_details' pk=prod.pk %}" class="buy-link">See more</a></th>
            </tr>
            {% endfor %}
        </table>
        {% bootstrap_pagination products_lists url=last_question %}
    {% else %}
        <p>Nothing found<br>Try to change your request</p>
    {% endif %}
{% endblock %}